#!/usr/bin/env python3
"""Batch-run Abaqus input files with a user subroutine.

Defaults are tailored to this workspace:
- Input files: project-local generated output folders
- User subroutine: ./truss_with_recruited_stretch_Ogden_hyperelastic_single_fiber.for

Examples
--------
Run the default generated cases:
    python run_abaqus_inp_batch.py

Dry-run the commands for the oriented generator output:y
    python run_abaqus_inp_batch.py --inp-dir rve_truss_histology_output_ps_oriented --dry-runy

Run only a subset with 8 CPUs:
    python run_abaqus_inp_batch.py rve_truss_histology_output_ps\\brain_wm_rve_truss_matrix_with_ps_uniaxial_x.inp ^
        rve_truss_histology_output_ps\\brain_wm_rve_truss_matrix_with_ps_uniaxial_y.inp --cpus 8
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Sequence


PROJECT_DIR = Path(__file__).resolve().parent
DEFAULT_INP_DIR_CANDIDATES = (
    PROJECT_DIR / "rve_truss_histology_output_ps",
    PROJECT_DIR / "rve_truss_histology_output_ps_oriented",
)
DEFAULT_USER_SUBROUTINE = (
    PROJECT_DIR / "truss_with_recruited_stretch_Ogden_hyperelastic_single_fiber.for"
)
SUMMARY_JSON_GLOB = "rve_truss_generation_summary*.json"


@dataclass(frozen=True)
class RunSpec:
    inp_path: Path
    job_name: str


@dataclass(frozen=True)
class JobAssessment:
    ok: bool
    reason: str


FAILURE_MARKERS = (
    "abaqus/standard analysis exited with an error",
    "abaqus/explicit analysis exited with an error",
    "abaqus/analysis exited with errors",
    "***error: the analysis has been terminated due to previous errors",
    "the analysis has not been completed",
    "error in job",
)

SUCCESS_MARKERS = (
    "the analysis has completed successfully",
    "job completed",
)


def sanitize_job_name(name: str) -> str:
    safe = []
    for ch in name.strip():
        if ch.isalnum() or ch in ("_", "-", "."):
            safe.append(ch)
        else:
            safe.append("_")
    out = "".join(safe).strip("._")
    return out or "abaqus_job"


def detect_default_inp_dir() -> Path:
    for candidate in DEFAULT_INP_DIR_CANDIDATES:
        if candidate.exists():
            return candidate
    return DEFAULT_INP_DIR_CANDIDATES[0]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run Abaqus .inp files with a user subroutine in batch."
    )
    parser.add_argument(
        "inputs",
        nargs="*",
        help="Optional .inp files or directories. If omitted, the default generated input directory is used.",
    )
    parser.add_argument(
        "--inp-dir",
        default=str(detect_default_inp_dir()),
        help="Directory to scan for input files when no explicit .inp files are provided.",
    )
    parser.add_argument(
        "--glob",
        default="*.inp",
        help="Glob pattern used when collecting input files from directories.",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Recursively search directories for matching .inp files.",
    )
    parser.add_argument(
        "--summary-json",
        default=None,
        help=(
            "Optional summary JSON generated by the RVE script. "
            "When provided, it is used to preserve the intended input-file order and Abaqus job names."
        ),
    )
    parser.add_argument(
        "--user-subroutine",
        default=str(DEFAULT_USER_SUBROUTINE),
        help="Path to the Abaqus user subroutine file (.for, .f, .f90, etc.).",
    )
    parser.add_argument(
        "--abaqus-cmd",
        default=None,
        help="Abaqus launcher command or full path. Defaults to ABAQUS_COMMAND env var or 'abaqus' on PATH.",
    )
    parser.add_argument(
        "--cpus",
        type=int,
        default=1,
        help="Number of CPUs passed to Abaqus for each job.",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        default=True,
        help="Run Abaqus with the 'interactive' flag (default: on).",
    )
    parser.add_argument(
        "--no-interactive",
        dest="interactive",
        action="store_false",
        help="Do not append the 'interactive' flag.",
    )
    parser.add_argument(
        "--double",
        action="store_true",
        help="Append 'double' to the Abaqus command.",
    )
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip jobs whose .odb file already exists next to the input file.",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Keep running the remaining jobs if one job fails.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the commands that would be run without executing Abaqus.",
    )
    return parser.parse_args()


def resolve_abaqus_command(cli_value: Optional[str]) -> str:
    candidates = [
        cli_value,
        os.environ.get("ABAQUS_COMMAND"),
        shutil.which("abaqus"),
        shutil.which("abq2024"),
        shutil.which("abq2023"),
    ]
    for candidate in candidates:
        if candidate:
            return candidate
    raise FileNotFoundError(
        "Could not locate the Abaqus command. Pass --abaqus-cmd or set ABAQUS_COMMAND."
    )


def discover_summary_json(search_dir: Path) -> Optional[Path]:
    candidates = sorted(search_dir.glob(SUMMARY_JSON_GLOB))
    if len(candidates) == 1:
        return candidates[0]
    return None


def load_specs_from_summary(summary_json: Path) -> List[RunSpec]:
    with summary_json.open("r", encoding="utf-8-sig") as f:
        data = json.load(f)

    specs: List[RunSpec] = []
    parent = summary_json.parent

    loading_cases = data.get("loading_cases", [])
    if loading_cases:
        for rec in loading_cases:
            file_name = rec.get("file_name")
            if not file_name:
                continue
            inp_path = parent / file_name
            if not inp_path.exists():
                raise FileNotFoundError(
                    f"Summary JSON references missing input file: {inp_path}"
                )
            job_name = sanitize_job_name(rec.get("job_name", inp_path.stem))
            specs.append(RunSpec(inp_path=inp_path, job_name=job_name))
        return specs

    for file_name in data.get("load_case_inp_files", []):
        inp_path = parent / file_name
        if not inp_path.exists():
            raise FileNotFoundError(
                f"Summary JSON references missing input file: {inp_path}"
            )
        specs.append(RunSpec(inp_path=inp_path, job_name=sanitize_job_name(inp_path.stem)))

    return specs


def collect_inp_files_from_dir(directory: Path, pattern: str, recursive: bool) -> List[Path]:
    if not directory.exists():
        raise FileNotFoundError(f"Input directory not found: {directory}")
    iterator = directory.rglob(pattern) if recursive else directory.glob(pattern)
    return sorted(p.resolve() for p in iterator if p.is_file())


def collect_run_specs(args: argparse.Namespace) -> List[RunSpec]:
    explicit_inp_files: List[Path] = []
    search_dirs: List[Path] = []

    for raw in args.inputs:
        path = Path(raw).expanduser().resolve()
        if path.is_file():
            explicit_inp_files.append(path)
        elif path.is_dir():
            search_dirs.append(path)
        else:
            raise FileNotFoundError(f"Input path not found: {path}")

    if explicit_inp_files:
        return [
            RunSpec(inp_path=path, job_name=sanitize_job_name(path.stem))
            for path in explicit_inp_files
        ]

    if not search_dirs:
        search_dirs = [Path(args.inp_dir).expanduser().resolve()]

    summary_json: Optional[Path] = None
    if args.summary_json:
        summary_json = Path(args.summary_json).expanduser().resolve()
        if not summary_json.exists():
            raise FileNotFoundError(f"Summary JSON not found: {summary_json}")
    elif len(search_dirs) == 1:
        summary_json = discover_summary_json(search_dirs[0])

    if summary_json is not None:
        return load_specs_from_summary(summary_json)

    inp_files: List[Path] = []
    for directory in search_dirs:
        inp_files.extend(collect_inp_files_from_dir(directory, args.glob, args.recursive))

    if not inp_files:
        raise FileNotFoundError(
            f"No input files matching '{args.glob}' were found in: "
            + ", ".join(str(d) for d in search_dirs)
        )

    unique_files = []
    seen = set()
    for inp_path in inp_files:
        key = str(inp_path).lower()
        if key in seen:
            continue
        seen.add(key)
        unique_files.append(inp_path)

    return [
        RunSpec(inp_path=path, job_name=sanitize_job_name(path.stem))
        for path in unique_files
    ]


def build_command(
    abaqus_cmd: str,
    spec: RunSpec,
    user_subroutine: Path,
    cpus: int,
    interactive: bool,
    use_double: bool,
) -> List[str]:
    command = [
        abaqus_cmd,
        f"job={spec.job_name}",
        f"input={spec.inp_path.name}",
        f"user={str(user_subroutine.resolve())}",
        f"cpus={cpus}",
    ]
    if use_double:
        command.append("double")
    if interactive:
        command.append("interactive")
    return command


def format_command_for_print(command: Sequence[str]) -> str:
    return subprocess.list2cmdline(list(command))


def read_text_tail(path: Path, max_bytes: int = 200_000) -> str:
    if not path.exists() or not path.is_file():
        return ""
    with path.open("rb") as f:
        f.seek(0, os.SEEK_END)
        size = f.tell()
        f.seek(max(0, size - max_bytes), os.SEEK_SET)
        data = f.read()
    return data.decode("latin-1", errors="ignore").lower()


def assess_job_artifacts(spec: RunSpec) -> JobAssessment:
    base = spec.inp_path.parent / spec.job_name
    odb_path = base.with_suffix(".odb")
    sta_path = base.with_suffix(".sta")
    msg_path = base.with_suffix(".msg")
    log_path = base.with_suffix(".log")
    dat_path = base.with_suffix(".dat")

    for path in (msg_path, log_path, sta_path, dat_path):
        text = read_text_tail(path)
        if not text:
            continue
        for marker in FAILURE_MARKERS:
            if marker in text:
                return JobAssessment(
                    ok=False,
                    reason=f"failure marker '{marker}' found in {path.name}",
                )

    if not odb_path.exists():
        return JobAssessment(ok=False, reason=f"missing output database: {odb_path.name}")

    for path in (sta_path, log_path, msg_path):
        text = read_text_tail(path)
        if not text:
            continue
        for marker in SUCCESS_MARKERS:
            if marker in text:
                return JobAssessment(
                    ok=True,
                    reason=f"success marker '{marker}' found in {path.name}",
                )

    return JobAssessment(
        ok=False,
        reason="no reliable Abaqus success marker was found in .sta/.log/.msg",
    )


def run_command(command: Sequence[str], cwd: Path) -> subprocess.CompletedProcess:
    command = list(command)
    if os.name == "nt":
        return subprocess.run(
            subprocess.list2cmdline(command),
            cwd=str(cwd),
            shell=True,
            check=False,
        )
    return subprocess.run(command, cwd=str(cwd), check=False)


def main() -> int:
    args = parse_args()

    user_subroutine = Path(args.user_subroutine).expanduser().resolve()
    if not user_subroutine.exists():
        raise FileNotFoundError(f"User subroutine not found: {user_subroutine}")
    if args.cpus < 1:
        raise ValueError("--cpus must be at least 1.")

    abaqus_cmd = resolve_abaqus_command(args.abaqus_cmd)
    specs = collect_run_specs(args)

    print(f"Abaqus command : {abaqus_cmd}")
    print(f"User subroutine: {user_subroutine}")
    print(f"Jobs to run    : {len(specs)}")
    print("")

    failures: List[RunSpec] = []

    for idx, spec in enumerate(specs, start=1):
        odb_path = spec.inp_path.with_name(f"{spec.job_name}.odb")
        if args.skip_existing and odb_path.exists():
            assessment = assess_job_artifacts(spec)
            if assessment.ok:
                print(f"[{idx}/{len(specs)}] Skipping existing successful job: {spec.job_name}")
                print(f"  Existing ODB: {odb_path}")
                print(f"  Check  : {assessment.reason}")
                continue
            print(f"[{idx}/{len(specs)}] Existing job artifacts are not valid for skip: {spec.job_name}")
            print(f"  Existing ODB: {odb_path}")
            print(f"  Check  : {assessment.reason}")
            print("  Action : rerunning job")

        command = build_command(
            abaqus_cmd=abaqus_cmd,
            spec=spec,
            user_subroutine=user_subroutine,
            cpus=args.cpus,
            interactive=args.interactive,
            use_double=args.double,
        )

        print(f"[{idx}/{len(specs)}] Running job: {spec.job_name}")
        print(f"  Input : {spec.inp_path}")
        print(f"  CWD   : {spec.inp_path.parent}")
        print(f"  Cmd   : {format_command_for_print(command)}")

        if args.dry_run:
            print("  Dry-run only; command not executed.")
            print("")
            continue

        result = run_command(command, cwd=spec.inp_path.parent)
        assessment = assess_job_artifacts(spec)
        if result.returncode == 0 and assessment.ok:
            print("  Status: completed")
            print(f"  Check : {assessment.reason}")
            print("")
            continue

        if result.returncode != 0:
            print(f"  Status: failed with exit code {result.returncode}")
        else:
            print("  Status: failed Abaqus artifact verification")
        print(f"  Check : {assessment.reason}")
        print("")
        failures.append(spec)
        if not args.continue_on_error:
            break

    if failures:
        print("Failed jobs:")
        for spec in failures:
            print(f"  - {spec.job_name} ({spec.inp_path})")
        return 1

    print("All requested Abaqus jobs finished.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(2)
